SURFACE_TYPE_PAND = 'pand'
SURFACE_TYPE_WEGDEEL = 'wegdeel'
SURFACE_TYPE_ONDERSTEUNENDWEGDEEL = 'ondersteunendwegdeel'
SURFACE_TYPE_BEGROEIDTERREINDEEL = 'begroeidterreindeel'
SURFACE_TYPE_ONBEGROEIDTERREINDEEL = 'onbegroeidterreindeel'
SURFACE_TYPE_WATERDEEL = 'waterdeel'
SURFACE_TYPE_ONDERSTEUNENDWATERDEEL = 'ondersteunendwaterdeel'
SURFACE_TYPE_OVERIGBOUWWERK = 'overigbouwwerk'
SURFACE_TYPE_GEBOUWINSTALLATIE = 'gebouwinstallatie'
SURFACE_TYPE_OVERBRUGGINGSDEEL = 'overbruggingsdeel'

ALL_USED_SURFACE_TYPES = {
    SURFACE_TYPE_PAND,
    SURFACE_TYPE_WEGDEEL,
    SURFACE_TYPE_ONDERSTEUNENDWEGDEEL,
    SURFACE_TYPE_BEGROEIDTERREINDEEL,
    SURFACE_TYPE_ONBEGROEIDTERREINDEEL,
    SURFACE_TYPE_WATERDEEL,
    SURFACE_TYPE_ONDERSTEUNENDWATERDEEL,
    SURFACE_TYPE_OVERIGBOUWWERK,
    SURFACE_TYPE_GEBOUWINSTALLATIE,
    SURFACE_TYPE_OVERBRUGGINGSDEEL
}

CONNECTABLE_SURFACE_TYPES = {
    SURFACE_TYPE_PAND,
    SURFACE_TYPE_WEGDEEL,
    SURFACE_TYPE_ONDERSTEUNENDWEGDEEL,
    SURFACE_TYPE_ONBEGROEIDTERREINDEEL,
    SURFACE_TYPE_OVERIGBOUWWERK
}

NON_CONNECTABLE_SURFACE_TYPES = {
    SURFACE_TYPE_BEGROEIDTERREINDEEL,
    SURFACE_TYPE_WATERDEEL,
    SURFACE_TYPE_ONDERSTEUNENDWATERDEEL,
    SURFACE_TYPE_GEBOUWINSTALLATIE,
    SURFACE_TYPE_OVERBRUGGINGSDEEL
}

assert CONNECTABLE_SURFACE_TYPES.union(NON_CONNECTABLE_SURFACE_TYPES) == ALL_USED_SURFACE_TYPES

SURFACE_TYPES_MET_FYSIEK_VOORKOMEN = {
    SURFACE_TYPE_WEGDEEL,
    SURFACE_TYPE_ONBEGROEIDTERREINDEEL,
    SURFACE_TYPE_ONDERSTEUNENDWEGDEEL
}

###############################

VERHARDINGSTYPE_PAND = 'pand'
VERHARDINGSTYPE_WATER = 'water'
VERHARDINGSTYPE_ONVERHARD = 'onverhard'
VERHARDINGSTYPE_OPEN_VERHARD = 'open verhard'
VERHARDINGSTYPE_GESLOTEN_VERHARD = 'gesloten verhard'

SOURCE_PIPES_TABLE_NAME = "default_lijn"


SURFACES_TABLE_NAME = 'bgt_oppervlak'
PIPES_TABLE_NAME = 'pipes'
BUILDINGS_TABLE_NAME = 'buildings'
RESULT_TABLE_NAME = 'bgt_inlooptabel'

RESULT_TABLE_FIELD_ID = 'id'
RESULT_TABLE_FIELD_LAATSTE_WIJZIGING = 'laatste_wijziging'
RESULT_TABLE_FIELD_BGT_IDENTIFICATIE = 'bgt_identificatie'
RESULT_TABLE_FIELD_TYPE_VERHARDING = 'type_verharding'
RESULT_TABLE_FIELD_GRAAD_VERHARDING = 'graad_verharding'
RESULT_TABLE_FIELD_HELLINGSTYPE = 'hellingstype'
RESULT_TABLE_FIELD_HELLINGSPERCENTAGE = 'hellingspercentage'
RESULT_TABLE_FIELD_BERGING_DAK = 'berging_dak'
RESULT_TABLE_FIELD_PUTCODE = 'putcode'
RESULT_TABLE_FIELD_LEIDINGCODE = 'leidingcode'

TARGET_TYPE_GEMENGD_RIOOL = 'gemengd_riool'
TARGET_TYPE_HEMELWATERRIOOL = 'hemelwaterriool'
TARGET_TYPE_VGS_HEMELWATERRIOOL = 'vgs_hemelwaterriool'
TARGET_TYPE_INFILTRATIEVOORZIENING = 'infiltratievoorziening'
TARGET_TYPE_NIET_AANGESLOTEN = 'niet_aangesloten'

FYSIEK_VOORKOMEN_VERHARD = ['verhard', 'open verharding', 'gesloten verharding', 'half verhard']

DISTANCE_TYPE_NAAM = {
    'Gemengd riool': 'gemengd_riool',
    'Hemelwaterriool': 'hemelwaterriool',
    'Vuilwaterriool': 'vuilwaterriool',
    'Infiltratieriool': 'infiltratievoorziening',
    # 'DIT-riool': # zou in dezelfde categorie moeten vallen als infiltratieriool, qua beslisboom
}

