# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BGTInloopTool
                                 A QGIS plugin
 BGT Inlooptool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-12
        copyright            : (C) 2020 by Emile de Badts
        email                : emile.debadts@nelen-schuurmans.nl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

from bgtinlooptool import dependencies

dependencies.ensure_everything_installed()

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name

    """Load BGTInloopTool class from file BGTInloopTool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """


        
    
    from .BGTInloopTool import BGTInloopTool
    return BGTInloopTool(iface)
