# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BGTInloopToolDialog
                                 A QGIS plugin
 BGT Inlooptool
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-08-12
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Emile de Badts
        email                : emile.debadts@nelen-schuurmans.nl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'BGTInloopTool_dialog_base.ui'))


class BGTInloopToolDialog(QtWidgets.QDialog, FORM_CLASS):
    
    def __init__(self, parent=None):
        """Constructor."""
        super(BGTInloopToolDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        
        # Setting defaults
        self.afstand_bgt_hemelwatervoorziening.setValue(40)
        self.afstand_verhardingsvlak_oppwater.setValue(2)
        self.afstand_pand_oppwater.setValue(6)
        self.afstand_verhardingsvlak_kolk.setValue(30)
        self.afstand_verhardingsvlak_kolk.setEnabled(False)
        
        self.afstand_afgekoppeld_stelsel.setValue(3)
        self.afstand_drievoudig_stelsel.setValue(4)

        self.bouwjaar_binnenhuisriolering.setMaximum(10000)
        self.bouwjaar_binnenhuisriolering.setValue(1992)
        self.bouwjaar_binnenhuisriolering.setEnabled(False)
        
        self.bag_panden_file.setEnabled(False)
        self.dem_file.setEnabled(False)
        self.kolken_file.setEnabled(False)
        
        self.checkbox_hellende_daken.setEnabled(False)