name: netheid
on:
  # Run on pushes to 'master' and pull requests (so: not branches as such, just the pull
  # request).
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  netheid:
    name: netheid
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v7
      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: 3.12
      - uses: pre-commit/action@v3.0.1
